name: care
description: "위듀 케어"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  carousel_slider: ^5.1.1
  go_router: ^16.2.0
  provider: ^6.1.5+1
  dio: ^5.9.0
  kakao_flutter_sdk_user: ^1.9.7+3
  sign_in_with_apple: ^7.0.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  flutter_naver_login: ^2.1.1
  step_progress: ^2.6.1
  daum_postcode_search: ^0.0.4
  flutter_inappwebview: ^6.1.5
  collection: ^1.19.1
  haptic_feedback: ^0.5.1+1
  fluttertoast: ^8.2.12
  flutter_native_splash: ^2.4.6
  table_calendar: ^3.2.0
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
